version: '3'

services:
  jaliri:
    build: .
    image: jaliri
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/jaliri
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/jaliri
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbvolume:/data/db
    networks:
      - node-network

volumes:
  dbvolume:

networks:
  node-network:
    driver: bridge
